apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/gitops-platform.git
    targetRevision: main
    path: environments/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
